package model;
// Generated 15/05/2019 21:27:16 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Additional generated by hbm2java
 */
@Entity
@Table(name="additional"
    ,schema="gcsystem"
)
public class Additional  implements java.io.Serializable {


     private int code;
     private Productcategory productcategory;
     private String description;
     private BigDecimal price;
     private Date datetimeins;
     private Set<Comboproductadditional> comboproductadditionals = new HashSet<Comboproductadditional>(0);
     private Set<Requestproductadditional> requestproductadditionals = new HashSet<Requestproductadditional>(0);
     private Set<Additionalcompany> additionalcompanies = new HashSet<Additionalcompany>(0);
     private Set<Productadditional> productadditionals = new HashSet<Productadditional>(0);

    public Additional() {
    }

	
    public Additional(int code) {
        this.code = code;
    }
    public Additional(int code, Productcategory productcategory, String description, BigDecimal price, Date datetimeins, Set<Comboproductadditional> comboproductadditionals, Set<Requestproductadditional> requestproductadditionals, Set<Additionalcompany> additionalcompanies, Set<Productadditional> productadditionals) {
       this.code = code;
       this.productcategory = productcategory;
       this.description = description;
       this.price = price;
       this.datetimeins = datetimeins;
       this.comboproductadditionals = comboproductadditionals;
       this.requestproductadditionals = requestproductadditionals;
       this.additionalcompanies = additionalcompanies;
       this.productadditionals = productadditionals;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_productcategory")
    public Productcategory getProductcategory() {
        return this.productcategory;
    }
    
    public void setProductcategory(Productcategory productcategory) {
        this.productcategory = productcategory;
    }

    
    @Column(name="description", length=40)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="price", precision=12)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datetimeins", length=29)
    public Date getDatetimeins() {
        return this.datetimeins;
    }
    
    public void setDatetimeins(Date datetimeins) {
        this.datetimeins = datetimeins;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="additional")
    public Set<Comboproductadditional> getComboproductadditionals() {
        return this.comboproductadditionals;
    }
    
    public void setComboproductadditionals(Set<Comboproductadditional> comboproductadditionals) {
        this.comboproductadditionals = comboproductadditionals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="additional")
    public Set<Requestproductadditional> getRequestproductadditionals() {
        return this.requestproductadditionals;
    }
    
    public void setRequestproductadditionals(Set<Requestproductadditional> requestproductadditionals) {
        this.requestproductadditionals = requestproductadditionals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="additional")
    public Set<Additionalcompany> getAdditionalcompanies() {
        return this.additionalcompanies;
    }
    
    public void setAdditionalcompanies(Set<Additionalcompany> additionalcompanies) {
        this.additionalcompanies = additionalcompanies;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="additional")
    public Set<Productadditional> getProductadditionals() {
        return this.productadditionals;
    }
    
    public void setProductadditionals(Set<Productadditional> productadditionals) {
        this.productadditionals = productadditionals;
    }




}


