package model;
// Generated 12/05/2019 21:50:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Additional generated by hbm2java
 */
@Entity
@Table(name="additional"
    ,schema="gcsystem"
)
public class Additional  implements java.io.Serializable {


     private int code;
     private Productcategory productcategory;
     private String description;
     private float price;
     private Character active;
     private Date datetimeins;
     private Set<Requestproductadditional> requestproductadditionals = new HashSet<Requestproductadditional>(0);
     private Set<Additionalproduct> additionalproducts = new HashSet<Additionalproduct>(0);

    public Additional() {
        price=4;
    }

	
    public Additional(int code) {
        this.code = code;
    }
    public Additional(int code, Productcategory productcategory, String description, float price, Character active, Date datetimeins, Set<Requestproductadditional> requestproductadditionals, Set<Additionalproduct> additionalproducts) {
       this.code = code;
       this.productcategory = productcategory;
       this.description = description;
       this.price = price;
       this.active = active;
       this.datetimeins = datetimeins;
       this.requestproductadditionals = requestproductadditionals;
       this.additionalproducts = additionalproducts;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_productcategory")
    public Productcategory getProductcategory() {
        return this.productcategory;
    }
    
    public void setProductcategory(Productcategory productcategory) {
        this.productcategory = productcategory;
    }

    
    @Column(name="description", length=40)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="price", precision=12)
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }

    
    @Column(name="active", length=1)
    public Character getActive() {
        return this.active;
    }
    
    public void setActive(Character active) {
        this.active = active;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datetimeins", length=29)
    public Date getDatetimeins() {
        return this.datetimeins;
    }
    
    public void setDatetimeins(Date datetimeins) {
        this.datetimeins = datetimeins;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="additional")
    public Set<Requestproductadditional> getRequestproductadditionals() {
        return this.requestproductadditionals;
    }
    
    public void setRequestproductadditionals(Set<Requestproductadditional> requestproductadditionals) {
        this.requestproductadditionals = requestproductadditionals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="additional")
    public Set<Additionalproduct> getAdditionalproducts() {
        return this.additionalproducts;
    }
    
    public void setAdditionalproducts(Set<Additionalproduct> additionalproducts) {
        this.additionalproducts = additionalproducts;
    }




}


