package model;
// Generated 25/04/2019 00:40:20 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Additional generated by hbm2java
 */
@Entity
@Table(name="additional"
    ,schema="gcsystem"
)
public class Additional  implements java.io.Serializable {


     private int code;
     private Category category;
     private String description;
     private BigDecimal price;
     private String active;
     private Set<Requestadditionalitem> requestadditionalitems = new HashSet<Requestadditionalitem>(0);
     private Set<Additionalitem> additionalitems = new HashSet<Additionalitem>(0);

    public Additional() {
    }

	
    public Additional(int code, Category category) {
        this.code = code;
        this.category = category;
    }
    public Additional(int code, Category category, String description, BigDecimal price, String active, Set<Requestadditionalitem> requestadditionalitems, Set<Additionalitem> additionalitems) {
       this.code = code;
       this.category = category;
       this.description = description;
       this.price = price;
       this.active = active;
       this.requestadditionalitems = requestadditionalitems;
       this.additionalitems = additionalitems;
    }
   
     @Id 

    
    @Column(name="code", nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_category", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="description", length=40)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="price", precision=6)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    
    @Column(name="active", length=3)
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="additional")
    public Set<Requestadditionalitem> getRequestadditionalitems() {
        return this.requestadditionalitems;
    }
    
    public void setRequestadditionalitems(Set<Requestadditionalitem> requestadditionalitems) {
        this.requestadditionalitems = requestadditionalitems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="additional")
    public Set<Additionalitem> getAdditionalitems() {
        return this.additionalitems;
    }
    
    public void setAdditionalitems(Set<Additionalitem> additionalitems) {
        this.additionalitems = additionalitems;
    }




}


