package model;
// Generated 15/05/2019 21:27:16 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Additionalcompany generated by hbm2java
 */
@Entity
@Table(name="additionalcompany"
    ,schema="gcsystem"
)
public class Additionalcompany  implements java.io.Serializable {


     private int code;
     private Additional additional;
     private Company company;
     private Boolean available;

    public Additionalcompany() {
    }

	
    public Additionalcompany(int code) {
        this.code = code;
    }
    public Additionalcompany(int code, Additional additional, Company company, Boolean available) {
       this.code = code;
       this.additional = additional;
       this.company = company;
       this.available = available;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_additional")
    public Additional getAdditional() {
        return this.additional;
    }
    
    public void setAdditional(Additional additional) {
        this.additional = additional;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }

    
    @Column(name="available")
    public Boolean getAvailable() {
        return this.available;
    }
    
    public void setAvailable(Boolean available) {
        this.available = available;
    }




}


