package model;
// Generated 19/05/2019 14:54:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Comboproductadditional generated by hbm2java
 */
@Entity
@Table(name="comboproductadditional"
    ,schema="gcsystem"
)
public class Comboproductadditional  implements java.io.Serializable {


     private int code;
     private Additional additional;
     private Comboproduct comboproduct;

    public Comboproductadditional() {
    }

	
    public Comboproductadditional(int code) {
        this.code = code;
    }
    public Comboproductadditional(int code, Additional additional, Comboproduct comboproduct) {
       this.code = code;
       this.additional = additional;
       this.comboproduct = comboproduct;
    }
   
     @Id 

    
    @Column(name="code", nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_additional")
    public Additional getAdditional() {
        return this.additional;
    }
    
    public void setAdditional(Additional additional) {
        this.additional = additional;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_comboproduct")
    public Comboproduct getComboproduct() {
        return this.comboproduct;
    }
    
    public void setComboproduct(Comboproduct comboproduct) {
        this.comboproduct = comboproduct;
    }




}


