package model;
// Generated 19/05/2019 14:54:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Comboproduct generated by hbm2java
 */
@Entity
@Table(name="comboproduct"
    ,schema="gcsystem"
)
public class Comboproduct  implements java.io.Serializable {


     private int code;
     private Product productByCodeProduct;
     private Product productByCodeComboproduct;
     private Integer countproduct;
     private Set<Comboproductadditional> comboproductadditionals = new HashSet<Comboproductadditional>(0);

    public Comboproduct() {
    }

	
    public Comboproduct(int code) {
        this.code = code;
    }
    public Comboproduct(int code, Product productByCodeProduct, Product productByCodeComboproduct, Integer countproduct, Set<Comboproductadditional> comboproductadditionals) {
       this.code = code;
       this.productByCodeProduct = productByCodeProduct;
       this.productByCodeComboproduct = productByCodeComboproduct;
       this.countproduct = countproduct;
       this.comboproductadditionals = comboproductadditionals;
    }
   
     @Id 

    
    @Column(name="code", nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_product")
    public Product getProductByCodeProduct() {
        return this.productByCodeProduct;
    }
    
    public void setProductByCodeProduct(Product productByCodeProduct) {
        this.productByCodeProduct = productByCodeProduct;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_comboproduct")
    public Product getProductByCodeComboproduct() {
        return this.productByCodeComboproduct;
    }
    
    public void setProductByCodeComboproduct(Product productByCodeComboproduct) {
        this.productByCodeComboproduct = productByCodeComboproduct;
    }

    
    @Column(name="countproduct")
    public Integer getCountproduct() {
        return this.countproduct;
    }
    
    public void setCountproduct(Integer countproduct) {
        this.countproduct = countproduct;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comboproduct")
    public Set<Comboproductadditional> getComboproductadditionals() {
        return this.comboproductadditionals;
    }
    
    public void setComboproductadditionals(Set<Comboproductadditional> comboproductadditionals) {
        this.comboproductadditionals = comboproductadditionals;
    }




}


