package model;
// Generated 12/05/2019 21:50:56 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Filterhistory generated by hbm2java
 */
@Entity
@Table(name="filterhistory"
    ,schema="gcsystem"
)
public class Filterhistory  implements java.io.Serializable {


     private int code;
     private Productcategory productcategory;
     private Integer codeUserlogin;

    public Filterhistory() {
    }

	
    public Filterhistory(int code) {
        this.code = code;
    }
    public Filterhistory(int code, Productcategory productcategory, Integer codeUserlogin) {
       this.code = code;
       this.productcategory = productcategory;
       this.codeUserlogin = codeUserlogin;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_productcategory")
    public Productcategory getProductcategory() {
        return this.productcategory;
    }
    
    public void setProductcategory(Productcategory productcategory) {
        this.productcategory = productcategory;
    }

    
    @Column(name="code_userlogin")
    public Integer getCodeUserlogin() {
        return this.codeUserlogin;
    }
    
    public void setCodeUserlogin(Integer codeUserlogin) {
        this.codeUserlogin = codeUserlogin;
    }




}


