package model;
// Generated 19/05/2019 14:54:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Filterhistory generated by hbm2java
 */
@Entity
@Table(name="filterhistory"
    ,schema="gcsystem"
)
public class Filterhistory  implements java.io.Serializable {


     private int code;
     private Productcategory productcategory;
     private Userlogin userlogin;

    public Filterhistory() {
    }

	
    public Filterhistory(int code) {
        this.code = code;
    }
    public Filterhistory(int code, Productcategory productcategory, Userlogin userlogin) {
       this.code = code;
       this.productcategory = productcategory;
       this.userlogin = userlogin;
    }
   
     @Id 

    
    @Column(name="code", nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_productcategory")
    public Productcategory getProductcategory() {
        return this.productcategory;
    }
    
    public void setProductcategory(Productcategory productcategory) {
        this.productcategory = productcategory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_userlogin")
    public Userlogin getUserlogin() {
        return this.userlogin;
    }
    
    public void setUserlogin(Userlogin userlogin) {
        this.userlogin = userlogin;
    }




}


