package model;
// Generated 25/04/2019 00:40:20 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Filterhistory generated by hbm2java
 */
@Entity
@Table(name = "filterhistory", schema = "gcsystem")
public class Filterhistory implements java.io.Serializable {

    private int code;
    private Category category;
    private Userlogin userlogin;

    public Filterhistory() {
    }

    public Filterhistory(int code, Category category, Userlogin userlogin) {
        this.code = code;
        this.category = category;
        this.userlogin = userlogin;
    }

    @Id

    @Column(name = "code", nullable = false)
    public int getCode() {
        return this.code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "code_category", nullable = false)
    public Category getCategory() {
        return this.category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "code_userlogin", nullable = false)
    public Userlogin getUserlogin() {
        return this.userlogin;
    }

    public void setUserlogin(Userlogin userlogin) {
        this.userlogin = userlogin;
    }

}
