package model;
// Generated 19/05/2019 14:54:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Itemcompany generated by hbm2java
 */
@Entity
@Table(name="itemcompany"
    ,schema="dksystem"
)
public class Itemcompany  implements java.io.Serializable {


     private int code;
     private Company company;
     private Item item;
     private Character priority;
     private BigDecimal quantity;
     private BigDecimal maxstock;
     private BigDecimal minstock;
     private Boolean active;

    public Itemcompany() {
    }

	
    public Itemcompany(int code) {
        this.code = code;
    }
    public Itemcompany(int code, Company company, Item item, Character priority, BigDecimal quantity, BigDecimal maxstock, BigDecimal minstock, Boolean active) {
       this.code = code;
       this.company = company;
       this.item = item;
       this.priority = priority;
       this.quantity = quantity;
       this.maxstock = maxstock;
       this.minstock = minstock;
       this.active = active;
    }
   
     @Id 

    
    @Column(name="code", nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_item")
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }

    
    @Column(name="priority", length=1)
    public Character getPriority() {
        return this.priority;
    }
    
    public void setPriority(Character priority) {
        this.priority = priority;
    }

    
    @Column(name="quantity", precision=12)
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="maxstock", precision=12)
    public BigDecimal getMaxstock() {
        return this.maxstock;
    }
    
    public void setMaxstock(BigDecimal maxstock) {
        this.maxstock = maxstock;
    }

    
    @Column(name="minstock", precision=12)
    public BigDecimal getMinstock() {
        return this.minstock;
    }
    
    public void setMinstock(BigDecimal minstock) {
        this.minstock = minstock;
    }

    
    @Column(name="active")
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }




}


