package model;
// Generated 19/05/2019 14:54:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Productadditional generated by hbm2java
 */
@Entity
@Table(name="productadditional"
    ,schema="gcsystem"
)
public class Productadditional  implements java.io.Serializable {


     private int code;
     private Additional additional;
     private Product product;

    public Productadditional() {
    }

	
    public Productadditional(int code) {
        this.code = code;
    }
    public Productadditional(int code, Additional additional, Product product) {
       this.code = code;
       this.additional = additional;
       this.product = product;
    }
   
     @Id 

    
    @Column(name="code", nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_additional")
    public Additional getAdditional() {
        return this.additional;
    }
    
    public void setAdditional(Additional additional) {
        this.additional = additional;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_product")
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }




}


