package model;
// Generated 19/05/2019 14:54:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Productcompany generated by hbm2java
 */
@Entity
@Table(name="productcompany"
    ,schema="gcsystem"
)
public class Productcompany  implements java.io.Serializable {


     private int code;
     private Company company;
     private Product product;
     private Boolean available;

    public Productcompany() {
    }

	
    public Productcompany(int code) {
        this.code = code;
    }
    public Productcompany(int code, Company company, Product product, Boolean available) {
       this.code = code;
       this.company = company;
       this.product = product;
       this.available = available;
    }
   
     @Id 

    
    @Column(name="code", nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_product")
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="available")
    public Boolean getAvailable() {
        return this.available;
    }
    
    public void setAvailable(Boolean available) {
        this.available = available;
    }




}


