package model;
// Generated 15/05/2019 21:27:16 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Requestproductadditional generated by hbm2java
 */
@Entity
@Table(name="requestproductadditional"
    ,schema="gcsystem"
)
public class Requestproductadditional  implements java.io.Serializable {


     private int code;
     private Additional additional;
     private Requestproduct requestproduct;

    public Requestproductadditional() {
    }

	
    public Requestproductadditional(int code) {
        this.code = code;
    }
    public Requestproductadditional(int code, Additional additional, Requestproduct requestproduct) {
       this.code = code;
       this.additional = additional;
       this.requestproduct = requestproduct;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_additional")
    public Additional getAdditional() {
        return this.additional;
    }
    
    public void setAdditional(Additional additional) {
        this.additional = additional;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_requestproduct")
    public Requestproduct getRequestproduct() {
        return this.requestproduct;
    }
    
    public void setRequestproduct(Requestproduct requestproduct) {
        this.requestproduct = requestproduct;
    }




}


