package model;
// Generated 15/05/2019 21:27:16 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Requestproduct generated by hbm2java
 */
@Entity
@Table(name="requestproduct"
    ,schema="gcsystem"
)
public class Requestproduct  implements java.io.Serializable {


     private int code;
     private Product product;
     private Request request;
     private String status;
     private Integer countproduct;
     private String note;
     private Boolean requeststart;
     private Date datetimeins;
     private Date datetimeupd;
     private Set<Requestproductadditional> requestproductadditionals = new HashSet<Requestproductadditional>(0);

    public Requestproduct() {
    }

	
    public Requestproduct(int code) {
        this.code = code;
    }
    public Requestproduct(int code, Product product, Request request, String status, Integer countproduct, String note, Boolean requeststart, Date datetimeins, Date datetimeupd, Set<Requestproductadditional> requestproductadditionals) {
       this.code = code;
       this.product = product;
       this.request = request;
       this.status = status;
       this.countproduct = countproduct;
       this.note = note;
       this.requeststart = requeststart;
       this.datetimeins = datetimeins;
       this.datetimeupd = datetimeupd;
       this.requestproductadditionals = requestproductadditionals;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_product")
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_request")
    public Request getRequest() {
        return this.request;
    }
    
    public void setRequest(Request request) {
        this.request = request;
    }

    
    @Column(name="status", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="countproduct")
    public Integer getCountproduct() {
        return this.countproduct;
    }
    
    public void setCountproduct(Integer countproduct) {
        this.countproduct = countproduct;
    }

    
    @Column(name="note", length=150)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="requeststart")
    public Boolean getRequeststart() {
        return this.requeststart;
    }
    
    public void setRequeststart(Boolean requeststart) {
        this.requeststart = requeststart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datetimeins", length=29)
    public Date getDatetimeins() {
        return this.datetimeins;
    }
    
    public void setDatetimeins(Date datetimeins) {
        this.datetimeins = datetimeins;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datetimeupd", length=29)
    public Date getDatetimeupd() {
        return this.datetimeupd;
    }
    
    public void setDatetimeupd(Date datetimeupd) {
        this.datetimeupd = datetimeupd;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="requestproduct")
    public Set<Requestproductadditional> getRequestproductadditionals() {
        return this.requestproductadditionals;
    }
    
    public void setRequestproductadditionals(Set<Requestproductadditional> requestproductadditionals) {
        this.requestproductadditionals = requestproductadditionals;
    }




}


