package model;
// Generated 12/05/2019 21:50:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tablelist generated by hbm2java
 */
@Entity
@Table(name="tablelist"
    ,schema="gcsystem"
    , uniqueConstraints = @UniqueConstraint(columnNames="description") 
)
public class Tablelist  implements java.io.Serializable {


     private int code;
     private String description;
     private Character active;
     private Integer codeCompany;
     private Set<Request> requests = new HashSet<Request>(0);

    public Tablelist() {
    }

	
    public Tablelist(int code) {
        this.code = code;
    }
    public Tablelist(int code, String description, Character active, Integer codeCompany, Set<Request> requests) {
       this.code = code;
       this.description = description;
       this.active = active;
       this.codeCompany = codeCompany;
       this.requests = requests;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

    
    @Column(name="description", unique=true, length=10)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="active", length=1)
    public Character getActive() {
        return this.active;
    }
    
    public void setActive(Character active) {
        this.active = active;
    }

    
    @Column(name="code_company")
    public Integer getCodeCompany() {
        return this.codeCompany;
    }
    
    public void setCodeCompany(Integer codeCompany) {
        this.codeCompany = codeCompany;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tablelist")
    public Set<Request> getRequests() {
        return this.requests;
    }
    
    public void setRequests(Set<Request> requests) {
        this.requests = requests;
    }




}


