package model;
// Generated 25/04/2019 00:40:20 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Userpermission generated by hbm2java
 */
@Entity
@Table(name = "userpermission", schema = "gcsystem")
public class Userpermission implements java.io.Serializable {

    private int code;
    private Userlogin userlogin;
    private Character cashier;
    private Character attendant;

    public Userpermission() {
    }

    public Userpermission(Userlogin userlogin) {
        this.userlogin = userlogin;
    }

    public Userpermission(Userlogin userlogin, Character cashier, Character attendant) {
        this.userlogin = userlogin;
        this.cashier = cashier;
        this.attendant = attendant;
    }

    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "userlogin"))
    @Id
    @GeneratedValue(generator = "generator")

    @Column(name = "code", nullable = false)
    public int getCode() {
        return this.code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public Userlogin getUserlogin() {
        return this.userlogin;
    }

    public void setUserlogin(Userlogin userlogin) {
        this.userlogin = userlogin;
    }

    @Column(name = "cashier", length = 1)
    public Character getCashier() {
        return this.cashier;
    }

    public void setCashier(Character cashier) {
        this.cashier = cashier;
    }

    @Column(name = "attendant", length = 1)
    public Character getAttendant() {
        return this.attendant;
    }

    public void setAttendant(Character attendant) {
        this.attendant = attendant;
    }

}
