package model;
// Generated 13/05/2019 02:38:28 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,schema="gcsystem"
)
public class Product  implements java.io.Serializable {


     private int code;
     private String barcode;
     private String description;
     private BigDecimal price;
     private String preparation;
     private String additional;
     private Character active;
     private Date datetimeins;
     private Set<Requestproduct> requestproducts = new HashSet<Requestproduct>(0);

    public Product() {
    }

	
    public Product(int code) {
        this.code = code;
    }
    public Product(int code, String barcode, String description, BigDecimal price, String preparation, String additional, Character active, Date datetimeins, Set<Requestproduct> requestproducts) {
       this.code = code;
       this.barcode = barcode;
       this.description = description;
       this.price = price;
       this.preparation = preparation;
       this.additional = additional;
       this.active = active;
       this.datetimeins = datetimeins;
       this.requestproducts = requestproducts;
     }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

    @Column(name="barcode", length=9)
    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    
    @Column(name="description", length=40)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="price", precision=12)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    
    @Column(name="preparation", length=20)
    public String getPreparation() {
        return this.preparation;
    }
    
    public void setPreparation(String preparation) {
        this.preparation = preparation;
    }

    
    @Column(name="additional", length=3)
    public String getAdditional() {
        return this.additional;
    }
    
    public void setAdditional(String additional) {
        this.additional = additional;
    }

    
    @Column(name="active", length=1)
    public Character getActive() {
        return this.active;
    }
    
    public void setActive(Character active) {
        this.active = active;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datetimeins", length=29)
    public Date getDatetimeins() {
        return this.datetimeins;
    }
    
    public void setDatetimeins(Date datetimeins) {
        this.datetimeins = datetimeins;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<Requestproduct> getRequestproducts() {
        return this.requestproducts;
    }
    
    public void setRequestproducts(Set<Requestproduct> requestproducts) {
        this.requestproducts = requestproducts;
    }

}


