package model;
// Generated 13/05/2019 02:38:28 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Requestproduct generated by hbm2java
 */
@Entity
@Table(name = "requestproduct", schema = "gcsystem"
)
public class Requestproduct implements java.io.Serializable {

    private int code;
    private Product product;
    private Teste teste;
    private String status;
    private Integer countproduct;
    private String note;
    private Character requeststart;
    private Date datetimeins;
    private Date datetimeupd;
   
    public Requestproduct() {
    }

    public Requestproduct(Teste teste) {
        this.teste = teste;
    }

    public Requestproduct(Product product, Teste teste, String status, Integer countproduct, String note, Character requeststart, Date datetimeins, Date datetimeupd) {
        this.product = product;
        this.teste = teste;
        this.status = status;
        this.countproduct = countproduct;
        this.note = note;
        this.requeststart = requeststart;
        this.datetimeins = datetimeins;
        this.datetimeupd = datetimeupd;
    }

    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "teste"))
    @Id
    @GeneratedValue(generator = "generator")

    @Column(name = "code", unique = true, nullable = false)
    public int getCode() {
        return this.code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "code_product")
    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public Teste getTeste() {
        return this.teste;
    }

    public void setTeste(Teste teste) {
        this.teste = teste;
    }

    @Column(name = "status", length = 20)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "countproduct")
    public Integer getCountproduct() {
        return this.countproduct;
    }

    public void setCountproduct(Integer countproduct) {
        this.countproduct = countproduct;
    }

    @Column(name = "note", length = 150)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    @Column(name = "requeststart", length = 1)
    public Character getRequeststart() {
        return this.requeststart;
    }

    public void setRequeststart(Character requeststart) {
        this.requeststart = requeststart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "datetimeins", length = 29)
    public Date getDatetimeins() {
        return this.datetimeins;
    }

    public void setDatetimeins(Date datetimeins) {
        this.datetimeins = datetimeins;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "datetimeupd", length = 29)
    public Date getDatetimeupd() {
        return this.datetimeupd;
    }

    public void setDatetimeupd(Date datetimeupd) {
        this.datetimeupd = datetimeupd;
    }

}
