package model;
// Generated 13/05/2019 02:38:28 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Teste generated by hbm2java
 */
@Entity
@Table(name="teste"
    ,schema="gcsystem"
)
public class Teste  implements java.io.Serializable {


     private int code;
     private Requestproduct requestproduct;

    public Teste() {
    }

	
    public Teste(int code) {
        this.code = code;
    }
    public Teste(int code, Requestproduct requestproduct) {
       this.code = code;
       this.requestproduct = requestproduct;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="teste")
    public Requestproduct getRequestproduct() {
        return this.requestproduct;
    }
    
    public void setRequestproduct(Requestproduct requestproduct) {
        this.requestproduct = requestproduct;
    }




}


